### ISSUE TITLE
extractFull failed

### ISSUE THREAD

**Issue by mader89** [quentinrossetti/node-7z#107]
stderr: 'ERROR: Cannot open output file : '**\\chrome_elf.dll\r\n',   \r\n ，解析压缩包失败，dll末尾多了一个换行符(\r\n)

**Comment by mader89** [comment]
at Object.fromBuffer (evalmachine.<anonymous>:1:667857)
    at evalmachine.<anonymous>:1:667319
    at Socket.<anonymous> (evalmachine.<anonymous>:1:647297)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  stderr: 'ERROR: Cannot open output file :**\\chrome_elf.dll\r\n',

**Comment by mader89** [comment]
const 7zStream = extractFull(archive, output, {
                $bin: pathTo7zip,
                $progress: true,
                listFileCharset: 'WIN',
                charset: 'WIN'
            })

succeeded after adding ‘listFileCharset‘ option

**Comment by mader89** [comment]
Encoding problem, resolved
