### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by databasedude** [quentinrossetti/node-7z#12]
Here is the code that I'm trying to run on my Mac:

var Zip = require('node-7z');
var archive = new Zip();
archive.list('testArchive.7z', {})
    .progress(function (files) {
        // Do stuff with files...
    })
    .then(function () {
        // Do stuff...
    });

I get this error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

Any ideas how to resolve this?

Thanks

**Comment by databasedude** [comment]
Resolved
