### ISSUE TITLE
Adobe-CEP - Syntax-Error: Unexpected token

### ISSUE THREAD

**Issue by AtroCty** [quentinrossetti/node-7z#61]
In: 
```
...\CEP\extensions\com.atrocty.ExSphax\node_modules\node-7z\src\flags.js:9

Uncaught SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:567:28)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\CEP\extensions\com.atrocty.ExSphax\node_modules\node-7z\src\main.js:4:15)
```

I am enforced to use this Node.js 7.7.4:
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef

Is it possible to replace that token? Seems like ES6 doesn't support this kind of token.

**Comment by quentinrossetti** [comment]
Hi. This version on Node has reach end of life. Sorry but no support will be done for this.
https://github.com/nodejs/Release/blob/master/README.md
