### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by jeremylzy** [quentinrossetti/node-7z#74]
const BODY_PROGRESS = new RegExp('^ *(?<percent>\\d+)% ?(?<fileCount>\\d+)? ?(?<file>.*)$')
                      ^

SyntaxError: Invalid regular expression: /^ *(?<percent>\d+)% ?(?<fileCount>\d+)? ?(?<file>.*)$/: Invalid group
    at new RegExp (<anonymous>)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-7z\src\regexp.js:16:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-7z\src\parser.js:16:97)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

**Comment by hagen** [comment]
Make sure you're using node > 10

**Comment by quentinrossetti** [comment]
@hagen is right. This error happens with nodejs version before V10.
